### ISSUE TITLE
Auto-complete removes $ - ST3

### ISSUE THREAD

**Issue by mscarchilli** [maxhoffmann/angular-snippets#3]
In ST3:

The auto-complete of $scope (etc.) after pushing tab, removes the $ and leaves only "scope".

<img src="http://i.imgur.com/yqly1FX.jpg" />

<img src="http://i.imgur.com/oWYYYFg.jpg" />

**Comment by maxhoffmann** [comment]
I’ve tried to replicate the problem in ST3 and ST2, but it works correctly for me. Which OS do you use? What happens if you press enter instead of tab?

**Comment by mscarchilli** [comment]
I'm on Win7 x64. Pushing Enter just goes to the next line. Next chance I get, I'll test to see if another package is causing a conflict for whatever reason.

**Comment by maxhoffmann** [comment]
Okay, thanks. Let me know when you’ve found the cause.

**Comment by mscarchilli** [comment]
I removed all Packages and then added Package Control and AngularJS Snippets, and the same result is occurring. No User Key Bindings are set as well. I also changed it over so that "Return" would auto complete, and it had the same result.

**Comment by maxhoffmann** [comment]
Alright, I’ll try to get my hands on a windows machine and test it there. I wonder if you have any snippets installed that use $ and work? Maybe there are some jQuery snippets that you might try? If these don’t work the problem may lie somewhere else.

**Comment by noducks** [comment]
Am getting the same issue. I am on a Mac with ST3.  if I type $log and then select one of the items lets say $log.error from the dropdown. I end up getting a log.error('error') without the $, so I end up having to go back and enter the $. This happens whether it is a warning, info, log, etc.

**Comment by maxhoffmann** [comment]
I’m sorry, but I couldn’t find a way to replicate this bug. If someone is reading this, who could solve this issue I’d appreciate your help.
