### ISSUE TITLE
installed angular snippets, but not working

### ISSUE THREAD

**Issue by mlotfi2005** [maxhoffmann/angular-snippets#4]
Hi,
I installed angular-snippets in sublime Text 3 using Package Control,
when I open an HTML file, go for example just after <html , nothing happened.
Please your help is appreciated.
Thanks

**Comment by maxhoffmann** [comment]
I am aware of this issue. It seems that Sublime Text 3 handles auto completions in html differently. I could not yet find a way to show the completions list. Unfortunately there is very little documentation. If anyone solved this bug please post the solution here.

**Comment by maxhoffmann** [comment]
This bug seems to be fixed in the latest version of Sublime Text 3.
